Repository kugods-Homepage/kugods-server, pull requests merged in 2022-11, with the labels that each got.

#2 [Feat] 프로젝트 세팅
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  nest-cli.json
  package.json
  postgres.yml
  src/app/app.controller.spec.ts
  src/app/app.controller.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: feature

#5 Feat/4
  package-lock.json
  prisma/migrations/20221117102531_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  yarn.lock
Labels: DB migration

#8 [ETC] Update .prettierrc
  .prettierrc
Labels: chore

#11 [Feat] config & env validation
  package.json
  src/app/app.module.ts
  src/app/modules/config.module.ts
  yarn.lock
Labels: feature
